extends:
  [
    stylelint-config-recommended-scss,
    stylelint-config-prettier,
    '@wordpress/stylelint-config',
    '@wordpress/stylelint-config/scss',
  ]
rules:
  color-named: null
  selector-class-pattern: null
